namespace SubtitleAlchemist.Features.Options.Settings;

public enum ShortcutAction
{
    GeneralMergeSelectedLines,
    GeneralMergeWithPrevious,
    GeneralMergeWithNext,
    GeneralMergeWithPreviousAndUnbreak,
    GeneralMergeWithNextAndUnbreak,
    GeneralMergeWithPreviousAndAutoBreak,
    GeneralMergeWithNextAndAutoBreak,
    General,

    FileNew,
    FileOpen,
    FileOpenKeepVideo,
    FileSave,
    FileSaveAs,
    FileSaveAll,
    FileSaveOriginal,
    FileSaveOriginalAs,
    FileOpenOriginalSubtitle,
    FileCloseOriginalSubtitle,
    FileTranslatedSubtitle,
    FileCompare,
    FileImportPlainText,
    FileImportBluRaySupForOcr,
    FileImportBluRaySupForEdit,
    FileImportTimeCodes,
    FileExportEbuStl,
    FileExportPac,
    FileExportEdlClipName,
    FileExportPlainText,
    FileExportCustomTextFormat1,
    FileExportCustomTextFormat2,
    FileExportCustomTextFormat3,
    FileExit,

    EditFind,
    EditFindNext,
    EditReplace,
    EditMultipleReplace,
    EditModifySelection,
    EditGoToSubtitleNumber,

    Tools,
    SpellCheck,
    Video,
    Synchronization,
    Options,
    Translate,
    SubtitleListViewAndTextBox,
    SubtitleListView,
    SubtitleTextBox,
    WaveformAndSpectrogram,
}
